
site_name: New Zealand Dictionary Centre Database
nav: 
  - Overview: 'index.md'
  - Lexicon:
    - 'A' : 'A.md'
    - 'B' : 'B.md'

theme: mkdocs
   icon: fa-book
markdown_extensions:
  - toc:
      permalink: True
      baselevel: 1
      toc_depth: 3
 
extra_css: [extra.css]
